config/routes.rb
Rails.application.routes.draw do

  root to: 'customer/homes#top'
  get '/about', to: 'customer/homes#about'

  devise_for :customers, path: 'customer', controllers: {
  sessions:      'customer/sessions',
  passwords:     'customer/passwords',
  registrations: 'customer/registrations'
  }

  devise_for :admins, path: 'admin', controllers: {
  sessions:      'admin/sessions',
  passwords:     'admin/passwords',
  registrations: 'admin/registrations'
  }

  get 'orders/thanks' => 'customer/orders#thanks'
  get 'orders/confirm' => 'customer/orders#confirm'
  get "/customers/unsubscribe" => "customer/customers#unsubscribe"
  delete 'cart_items/destroy_all/:id' => 'customer/cart_items#destroy_all', as: "destroy_all"
  patch "/customers/withdraw" => "customer/customers#withdraw"


  get 'admin/orders/top' => 'admin/orders#top'
  patch 'admin/order_creates/:id' => 'admin/order_creates#update', as: "order_creates"



  scope module: :customer do
    resources :products, only: [:index, :show,]
    resources :cart_items, only: [:create, :index, :update, :destroy]
    resources :orders, only: [:index, :show, :new, :create]
    resources :receivers, except:[:new, :show]
    resource :customers, only:[:show, :edit, :update], as: "customer"
  end

  namespace :admin do
   resources :orders, only: [:index, :show, :update]
   resources :genres, only: [:index, :update, :edit, :create]
   resources :products, only: [:index, :new, :create, :show, :edit, :update]
   resources :customers, only:[:index, :edit, :update, :show]
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers=Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
    else
      render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:email, :family_name, :first_name, :family_kana, :first_kana, :postal_code, :address, :tel, :is_deleted)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def top
    @todayorder = Order.where(created_at: Time.current.all_day) #本日作成したOrderを代入
  end

  def index
    case params[:order_type]
    when "today"
      @orders = Order.where(created_at: Time.current.all_day)
    when "customer"
      @customer = Customer.find(params[:format])
      @orders = @customer.orders
    else
      @orders = Order.all  #注文履歴を降順(新しいものが一番上に)ページャ設定
    end
  end

  def update
    @order = Order.find(params[:id])
    order_products = OrderProduct.where(order_id: @order.id)
    @order.status = params[:status]
    @order.update(orders_params)
     if @order.status == "入金確認" #注文のステータスが「入金確認」になると紐付く注文商品ステータスを「制作待ち」にする
       order_products.each do |order_product|
         order_product.status = "製作待ち"
         order_product.update(order_creates_params)
       end
     end
    redirect_to request.referer
  end



  def show
    @order = Order.find(params[:id])
    @order_products = OrderProduct.where(order_id: @order.id)
  end

  private

  def orders_params
    params.require(:order).permit(:customer_id, :postal_code, :status, :address, :name, :shipping, :payment, :sum)
  end

  def order_creates_params
    params.permit(:product_id, :order_id, :quantity, :tax_in_price, :status)
  end

end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
 before_action :authenticate_customer!

  def index
    @carts = Cart.where(customer_id: current_customer.id)
    @subtotal = 0
    @total = 0
  end

  def create
    @cart = Cart.new(cart_params)
    @cart.customer_id = current_customer.id
    customercart = Cart.where(customer_id: current_customer.id)
    alreadycart = customercart.find_by(product_id: params[:id])
    if alreadycart
      alreadycart.quantity += params[:quantity].to_i
      alreadycart.save
    else
      @cart.product_id = params[:id]
      @cart.save
    end
    redirect_to cart_items_path(current_customer.id)
  end

  def update
    @cart = Cart.find(params[:id])
    @cart.quantity = params[:quantity]
    @cart.update(quantity_params)
    redirect_to request.referer
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    redirect_to request.referer
  end

  def destroy_all
    @cart = Cart.where(customer_id: params[:id])
    @cart.destroy_all
    redirect_to request.referer
  end

  private

  def cart_params
    params.permit(:product_id, :customer_id, :quantity)
  end

  def quantity_params
    params.permit(:quantity)
  end


end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  before_action :authenticate_customer!

  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
before_action :authenticate_customer!
  def show
    @customer = Customer.find(current_customer.id)
  end

  def edit
    @customer = Customer.find(current_customer.id)
  end

  def update
    @customer = Customer.find(current_customer.id)
    if @customer.update(customer_params)
      redirect_to customer_path(current_customer.id)
    else
      render :edit
    end
  end

  def unsubscribe
  end

  def withdraw
    customer = Customer.find(current_customer.id)
    customer.is_deleted = true                         #退会するボタンを押したとき現在ログインしているユーザーのis_deleteカラムをtrueに変えます。
    customer.update(customer_is_deleted)               #下で作成しているcustomer_is_deletedメソッドを呼び出しています
    reset_session                                       #セッションリセットによるログアウト処理
    redirect_to root_path                              #今はトップページに戻ってもログインしたままですが、ホクトさんにログイン状態の権限を設定してもらう予定です。
  end


  private
  def customer_params
     params.require(:customer).permit(:email, :family_name, :first_name, :family_kana, :first_kana, :postal_code, :address, :tel, :is_deleted)
  end

  def customer_is_deleted
     params.permit(:is_deleted)                  #require(:customer)を入れるとエラーが起きます。
  end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController

  def top
    @genres = Genre.where(is_active: "有効")
    @products = Product.where(genre_id: Genre.where(is_active: "有効")).last(4)
  end

  def about
  end

end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_action :authenticate_customer!

  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!

  def thanks
  end

  def index
    @order = Order.where(customer_id: current_customer.id).page(params[:page]).per(5).order(id: "DESC")  #降順に設定
  end

  def show
    @order = Order.find(params[:id])
    @order_products = OrderProduct.where(order_id: @order.id)
  end

  def new
    if Cart.find_by(customer_id: current_customer.id) == nil  #カート内商品が空ならカート画面に遷移
      redirect_to cart_items_path
    end
      @order = Order.new
      @customer = current_customer
      @receiver = current_customer
  end

  def create
    if Cart.where(customer_id: current_customer.id).count != 0  #カート内に商品があるかチェック、空ならトップページへ
      @order = Order.new(orders_params)
      @order.customer_id = current_customer.id
      if @order.save
        if params[:order][:select_name] == "2"
          receiver = Receiver.new(receivers_params)  #新しい配送先を登録
          receiver.customer_id = current_customer.id
          receiver.postal_code = @order.postal_code
          receiver.address = @order.address
          receiver.name = @order.name
          receiver.save
        end

        carts = Cart.where(customer_id: current_customer.id)
        carts.each do |cart|   #注文商品をorder_productモデルへ保存させる繰り返し処理
          order_product = OrderProduct.new(order_product_params)
          order_product.product_id = cart.product_id
          order_product.order_id = @order.id
          order_product.quantity = cart.quantity
          order_product.tax_in_price = cart.product.tax_out_price.to_i * 1.1
          order_product.save
        end
        carts.destroy_all
        redirect_to orders_thanks_path
      else
        @customer = current_customer
        @receiver = current_customer
        render :new
      end
    else
      redirect_to root_path
    end
  end

  def confirm
    @carts = Cart.where(customer_id: current_customer.id)
    @subtotal = 0
    @total = 0
    @order = Order.new(orders_params)
    @order.customer_id = current_customer.id
    # ご自身の住所なら
    if params[:order][:select_name] == "0"
      @order.address = current_customer.address
      @order.postal_code = current_customer.postal_code
      @order.name = current_customer.family_name + current_customer.first_name
      # 登録済み住所から選択なら
    elsif params[:order][:select_name] == "1"
      if params[:order][:receiver_id].blank?
        @customer = current_customer
        render :new
      else
        @receiver = Receiver.find(params[:order][:receiver_id])
        @order.address = @receiver.address
        @order.postal_code = @receiver.postal_code
        @order.name = @receiver.name
      end
      # 新しいお届け先なら
    elsif params[:order][:select_name] == "2"
      if params[:order][:postal_code].blank? || params[:order][:address].blank? || params[:order][:name].blank?
        @order = Order.new(orders_params)
        @customer = current_customer
        flash[:error] = "空欄があります"
        render :new
      else
        @order = Order.new(orders_params)
        @order.customer_id = current_customer.id
        @order.save
      end
    end
  end

  private
  def orders_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping, :payment, :sum)
  end

  def receiver_params
    params.require(:receiver).permit(:postal_code, :address, :name)
  end

  def order_product_params
    params.permit(:product_id, :order_id, :quantity, :tax_in_price, :status)
  end

  def receivers_params
    params.permit(:postal_code, :address, :name)
  end



end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  before_action :authenticate_customer!

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController
  before_action :authenticate_customer!, except: [:index, :show]

  def index
    @genres = Genre.where(is_active: "有効")

    if params[:id]
      @product = Product.where(genre_id: params[:id])
      @products = Product.where(genre_id: params[:id]).page(params[:page])
      @genre = Genre.find(params[:id])
    else
      @product = Product.where(genre_id: (Genre.where(is_active: "有効")))
      @products = Product.where(genre_id: (Genre.where(is_active: "有効"))).page(params[:page])
    end
  end

  def show
    @genres = Genre.all
    @product = Product.find(params[:id])
  end

  private

  def product_params
    params.require(@product).permit(:name, :tax_out_price)
  end


end

app/controllers/customer/receivers_controller.rb
class Customer::ReceiversController < ApplicationController
  before_action :authenticate_customer!

  def index
    @receiver = Receiver.new
    @receivers = Receiver.where(customer_id: current_customer.id)

  end

  def create
    @receiver = Receiver.new(receiver_params)
    @receiver.customer_id = current_customer.id
    if @receiver.save
      redirect_to receivers_path
    else
      @receivers = Receiver.where(customer_id: current_customer.id)
      render :index
    end
  end

  def edit
    @receiver = Receiver.find(params[:id])
    unless @receiver.customer_id == current_customer.id    #URL直打ち対策、ログインしている会員以外は編集一覧にとばされます
      redirect_to receivers_path
    end
  end

  def update
    @receiver = Receiver.find(params[:id])
    if @receiver.update(receiver_params)
      redirect_to receivers_path
    else
      render :edit
    end
  end

  def destroy
    receiver = Receiver.find(params[:id])
    receiver.destroy
    redirect_to receivers_path
  end

  private

  def receiver_params
    params.require(:receiver).permit(:postal_code, :address, :name)
  end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_customer!

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  before_action :authenticate_customer!
  before_action :reject_customer, only: [:create]

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  #def after_sign_in_path_for(resource)
  #  root_path
  #end

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false)) # active_for_authentication?アクションにより self.is_deleted == "有効"の際実行される
        flash[:danger] = "退会済です。"
        redirect_to new_customer_session_path
      end
    else
      flash[:danger] = "必須項目を入力してください。"
    end
  end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  before_action :authenticate_customer!

  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/views/customer/orders/confirm.html.erb
<main>
  <div class="container">

    <div class="row">
      <div class="col-9 mx-auto">
        <h3><span class="bg-secondary text-white">　注文情報確認　</span></h3><br>
      </div>
    </div>

    <div class="row">
      <div class ="col-8">
        <!--注文した商品の確認テーブル-->
        <table class="table table-bordered">
          <thead class="thead-light">
            <tr>
              <th>商品名</th>
              <th>単価（税込）</th>
              <th>数量</th>
              <th>小計</th>
            </tr>
          </thead>
          <tbody>
            <% @carts.each do |cart| %>
            <tr>
              <td class="align-middle"><%= attachment_image_tag cart.product, :image, size: "40x30", format: 'jpg', fallback: "no_image.jpg" %>
              　<%= cart.product.name %></td>
              <td class="align-middle"><%= ((cart.product.tax_out_price).to_i * 1.1).round %></td>
              <td class="align-middle"><%= cart.quantity %></td>
              <td class="align-middle"><%= ((cart.product.tax_out_price).to_i * 1.1 * (cart.quantity).to_i).round %></td>
              <% @subtotal = ((cart.product.tax_out_price).to_i * 1.1 * (cart.quantity).to_i).round %>
              <% @total = @total + @subtotal %>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-3">
        <!--注文した商品に関する金額-->
        <table class="table table-bordered">
          <tr><th class="table-active">送料</th><td><%= @order.shipping %></td></tr>
          <tr><th class="table-active">商品合計</th><td><%= @total %></td></tr>
          <tr><th class="table-active">請求金額</th><td><%= ((@order.shipping).to_i + (@total).to_i).round %></td></tr>
      </table>
      </div>
      <div class="col-1"></div>
    </div>

    <div class="row">
      <div class="col-7">
      <!--注文商品の支払い方法と配送先の確認-->
        <%= form_with model: @order, url: orders_path, method: :post, local: true do |f| %>
          <table class="table table-borderless">
          <tr><th class="align-middle"><h5>支払方法</h5></th><td><h5><%= @order.payment %></h5></td></tr>
          <tr><th class="align-middle"><h5>お届け先</h5></th>
          <td><h5>〒<%= @order.postal_code %><br>
                  <%= @order.address %><br>
                  <%= @order.name %></h5></td></tr>
          <%= f.hidden_field :payment, value: @order.payment %>
          <%= f.hidden_field :postal_code, value: @order.postal_code %>
          <%= f.hidden_field :address, value: @order.address %>
          <%= f.hidden_field :name, value: @order.name %>
          <%= f.hidden_field :sum, value: @total %>
          <%= f.hidden_field :select_name, value: params[:order][:select_name] %>
          </table>
      </div>
    </div>

    <div class="row justify-content-cente">
      <div class="col-3 mx-auto">
          <%= f.submit "購入を確定する", class: "btn btn-success btn-lg btn-block" %>
        <% end %>
      </div>
    </div>

  </div>
</main>

app/views/customer/orders/index.html.erb
<main>
  <div class="container">

    <div class="row">
      <div class="col-1"></div>
      <div class="col-3">
        <h3 class="text-center bg-light"><strong>注文履歴一覧</strong></h3>
      </div>
    </div>

    <div class="row mt-3">
      <div class ="col-10">
        <!--注文履歴一覧のテーブル-->
        <table class ="table table-bordered">
          <thead class="bg-light">
            <tr>
              <th class="www">注文日</th>
              <th>配送先</th>
              <th>注文商品</th>
              <th class="www">支払金額</th>
              <th class="www">ステータス</th>
              <th class="vvv">注文詳細</th>
            </tr>
          </thead>
          <tbody>
            <!--注文履歴の繰り返し処理-->
            <% @order.each do |order| %>
              <tr>
                <td><%= order.created_at.strftime('%Y/%m/%d') %></td>
                <td>〒<%= order.postal_code %><br><%= order.address %><br><%= order.name %></td>
                <td>
                  <% order.order_products.each do |order_product| %>
                    <li><%= order_product.product.name %></li>
                  <% end %>
                </td>
                <td class="text-right"><%= ((order.sum).to_i + (order.shipping).to_i).to_s(:delimited) %> 円</td>
                <td><%= order.status %></td>
                <td class="text-center"><%= link_to "表示する", order_path(order.id), class: "btn btn-primary btn-sm" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-5"></div>
      <div class="col-2 text-center">
        <span><%= paginate @order %></span>
      </div>
    </div>

  </div>
</main>

app/views/customer/orders/new.html.erb
<main>
  <div class="container">

    <div class="row">
      <div class="col-12">
      <!--注文情報入力フォーム-->
      <%= form_with model: @order, url: orders_confirm_path, method: :get, local: true do |f| %>
        <h4>支払方法</h4>
        <ul>
          <li><label><%= f.radio_button :payment, "銀行振込", :checked => true %>銀行振込</label></li>
          <li><label><%= f.radio_button :payment, "クレジットカード" %>クレジットカード</label></li>
        </ul>
        <h4>お届け先</h4>
        <ul>
          <!--ご自身の住所-->
          <li><label><%= f.radio_button :select_name, 0, :checked => true %>ご自身の住所</label></li>
            <%= f.label @customer.address %></br>
          <!--登録済み住所から選択-->
          <li><label><%= f.radio_button :select_name, 1 %>登録済み住所から選択</label></li>
            <%= f.collection_select :receiver_id, current_customer.receivers, :id, :address, include_blank: '選択してください'%>
          <!--新しいお届け先-->
          <li><label><%= f.radio_button :select_name, 2 %>新しいお届け先</label></li>
            <ul>
              <li><p>郵便番号（ハイフンなし）<%= f.text_field :postal_code %></p></li>
              <li><p><span class="text_field">住所</span><%= f.text_field :address, style: "width: 400px;" %></p></li>
              <li><p><span class="text_field">宛名</span><%= f.text_field :name %></p></li>
            </ul>
          <%= f.submit "確認画面へ進む", class:'btn btn-primary' %>
          <% unless flash[:error] == nil %><span class="deviseval alert alert-danger"><%= flash[:error] %></span><% end %>
        </ul>
      <% end %>
      </div>
    </div>

  </div>
</main>

app/views/customer/orders/show.html.erb
<main>
  <div class="container">

    <div class="row">
      <div class="col-1"></div>
      <div class="col-3">
        <h3 class="text-center bg-light"><strong>注文履歴詳細</strong></h3>
      </div>
    </div>

    <div class="row mt-4">
      <div class="col-7">
        <strong> &emsp; 注文情報</strong>
        <!--注文情報のテーブル-->
        <table class="table table-bordered mt-2">
          <tr>
            <td class="bg-light">注文日時</td>
            <td><%= @order.created_at.to_s(:datetime_jp) %></td>
          </tr>
          <tr>
            <td class="bg-light">配送先</td>
            <td>
              〒<%= @order.postal_code %>  &emsp; <%= @order.address %>
              <br><%= @order.name %>
            </td>
          </tr>
          <tr>
            <td class="bg-light">支払方法</td>
            <td><%= @order.payment %></td>
          </tr>
          <tr>
            <td class="bg-light">ステータス</td>
            <td><%= @order.status %></td>
          </tr>
        </table>
      </div>
      <div class="col-3">
        <strong> &emsp; 請求情報</strong>
        <!--注文による請求情報のテーブル-->
        <table class="table table-bordered mt-2">
          <tr>
            <td class="bg-light">商品合計</td>
            <td class="text-right"><%= @order.sum.to_s(:delimited) %> 円</td>
          </tr>
          <tr>
            <td class="bg-light">配送料</td>
            <td class="text-right"><%= @order.shipping %> 円</td>
          </tr>
          <tr>
            <th class="bg-light">ご請求額</th>
            <td class="text-right"><%= ((@order.sum).to_i  + (@order.shipping).to_i).to_s(:delimited) %> 円</td>
          </tr>
        </table>
      </div>
    </div>



    <div class="row mt-4">
      <div class="col-8">
        <strong> &emsp; 注文内容</strong>
        <!--注文した商品内容のテーブル-->
        <table class="table table-bordered mt-2">
          <thead class="bg-light">
            <tr>
              <td>商品</td>
              <td>単価（税込）</td>
              <td>個数</td>
              <th>小計</th>
            </tr>
          </thead>
          <tbody>
            <% @order_products.each do |order_product| %>
                <tr>
                  <td><%= order_product.product.name %></td>
                  <td class="zzz text-right"><%= order_product.tax_in_price.to_s(:delimited) %> 円</td>
                  <td class="zzz text-right"><%= order_product.quantity %> 個</td>
                  <td class="zzz text-right"><%= ((order_product.tax_in_price).to_i * (order_product.quantity).to_i).to_s(:delimited)%> 円</td>
                </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-2 d-flex align-items-center mt-5">
        <%= link_to "一覧画面へ戻る", orders_path, class: "btn btn-light" %>
      </div>
    </div>

  </div>
</main>

app/views/customer/orders/thanks.html.erb
<br>
<br>
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-9 mx-auto text-center">
      <h1>ご購入ありがとうございました！</h1>
      <br>
      <br>
      <br>
      <%= link_to "トップページに戻る", root_path, class: "btn btn-info" %>
    </div>
  </div>
</div>