config/routes.rb
Rails.application.routes.draw do

  root to: 'customer/homes#top'
  get '/about', to: 'customer/homes#about'

  devise_for :customers, path: 'customer', controllers: {
  sessions:      'customer/sessions',
  passwords:     'customer/passwords',
  registrations: 'customer/registrations'
  }

  devise_for :admins, path: 'admin', controllers: {
  sessions:      'admin/sessions',
  passwords:     'admin/passwords',
  registrations: 'admin/registrations'
  }

  get 'orders/thanks' => 'customer/orders#thanks'
  get 'orders/confirm' => 'customer/orders#confirm'
  get "/customers/unsubscribe" => "customer/customers#unsubscribe"
  delete 'cart_items/destroy_all/:id' => 'customer/cart_items#destroy_all', as: "destroy_all"
  patch "/customers/withdraw" => "customer/customers#withdraw"


  get 'admin/orders/top' => 'admin/orders#top'
  patch 'admin/order_creates/:id' => 'admin/order_creates#update', as: "order_creates"



  scope module: :customer do
    resources :products, only: [:index, :show,]
    resources :cart_items, only: [:create, :index, :update, :destroy]
    resources :orders, only: [:index, :show, :new, :create]
    resources :receivers, except:[:new, :show]
    resource :customers, only:[:show, :edit, :update], as: "customer"
  end

  namespace :admin do
   resources :orders, only: [:index, :show, :update]
   resources :genres, only: [:index, :update, :edit, :create]
   resources :products, only: [:index, :new, :create, :show, :edit, :update]
   resources :customers, only:[:index, :edit, :update, :show]
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products, dependent: :destroy
  belongs_to :customer

  validates :payment, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  # 支払方法
  enum payment: {銀行振込: 0, クレジットカード: 1}
  # 注文ステータス
  enum status: {入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def top
    @todayorder = Order.where(created_at: Time.current.all_day) #本日作成したOrderを代入
  end

  def index
    case params[:order_type]
    when "today"
      @orders = Order.where(created_at: Time.current.all_day)
    when "customer"
      @customer = Customer.find(params[:format])
      @orders = @customer.orders
    else
      @orders = Order.all  #注文履歴を降順(新しいものが一番上に)ページャ設定
    end
  end

  def update
    @order = Order.find(params[:id])
    order_products = OrderProduct.where(order_id: @order.id)
    @order.status = params[:status]
    @order.update(orders_params)
     if @order.status == "入金確認" #注文のステータスが「入金確認」になると紐付く注文商品ステータスを「制作待ち」にする
       order_products.each do |order_product|
         order_product.status = "製作待ち"
         order_product.update(order_creates_params)
       end
     end
    redirect_to request.referer
  end



  def show
    @order = Order.find(params[:id])
    @order_products = OrderProduct.where(order_id: @order.id)
  end

  private

  def orders_params
    params.require(:order).permit(:customer_id, :postal_code, :status, :address, :name, :shipping, :payment, :sum)
  end

  def order_creates_params
    params.permit(:product_id, :order_id, :quantity, :tax_in_price, :status)
  end

end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!

  def thanks
  end

  def index
    @order = Order.where(customer_id: current_customer.id).page(params[:page]).per(5).order(id: "DESC")  #降順に設定
  end

  def show
    @order = Order.find(params[:id])
    @order_products = OrderProduct.where(order_id: @order.id)
  end

  def new
    if Cart.find_by(customer_id: current_customer.id) == nil  #カート内商品が空ならカート画面に遷移
      redirect_to cart_items_path
    end
      @order = Order.new
      @customer = current_customer
      @receiver = current_customer
  end

  def create
    if Cart.where(customer_id: current_customer.id).count != 0  #カート内に商品があるかチェック、空ならトップページへ
      @order = Order.new(orders_params)
      @order.customer_id = current_customer.id
      if @order.save
        if params[:order][:select_name] == "2"
          receiver = Receiver.new(receivers_params)  #新しい配送先を登録
          receiver.customer_id = current_customer.id
          receiver.postal_code = @order.postal_code
          receiver.address = @order.address
          receiver.name = @order.name
          receiver.save
        end

        carts = Cart.where(customer_id: current_customer.id)
        carts.each do |cart|   #注文商品をorder_productモデルへ保存させる繰り返し処理
          order_product = OrderProduct.new(order_product_params)
          order_product.product_id = cart.product_id
          order_product.order_id = @order.id
          order_product.quantity = cart.quantity
          order_product.tax_in_price = cart.product.tax_out_price.to_i * 1.1
          order_product.save
        end
        carts.destroy_all
        redirect_to orders_thanks_path
      else
        @customer = current_customer
        @receiver = current_customer
        render :new
      end
    else
      redirect_to root_path
    end
  end

  def confirm
    @carts = Cart.where(customer_id: current_customer.id)
    @subtotal = 0
    @total = 0
    @order = Order.new(orders_params)
    @order.customer_id = current_customer.id
    # ご自身の住所なら
    if params[:order][:select_name] == "0"
      @order.address = current_customer.address
      @order.postal_code = current_customer.postal_code
      @order.name = current_customer.family_name + current_customer.first_name
      # 登録済み住所から選択なら
    elsif params[:order][:select_name] == "1"
      if params[:order][:receiver_id].blank?
        @customer = current_customer
        render :new
      else
        @receiver = Receiver.find(params[:order][:receiver_id])
        @order.address = @receiver.address
        @order.postal_code = @receiver.postal_code
        @order.name = @receiver.name
      end
      # 新しいお届け先なら
    elsif params[:order][:select_name] == "2"
      if params[:order][:postal_code].blank? || params[:order][:address].blank? || params[:order][:name].blank?
        @order = Order.new(orders_params)
        @customer = current_customer
        flash[:error] = "空欄があります"
        render :new
      else
        @order = Order.new(orders_params)
        @order.customer_id = current_customer.id
        @order.save
      end
    end
  end

  private
  def orders_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping, :payment, :sum)
  end

  def receiver_params
    params.require(:receiver).permit(:postal_code, :address, :name)
  end

  def order_product_params
    params.permit(:product_id, :order_id, :quantity, :tax_in_price, :status)
  end

  def receivers_params
    params.permit(:postal_code, :address, :name)
  end



end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/admin/orders/index.html.erb
<main>
  <div class="container">

    <div class="row">
      <div class="col-3">
        <h3 class="text-center bg-light"><strong>注文履歴一覧</strong></h3>
      </div>
    </div>
    <div class="row make">
      <table class="table">
        <thead>
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <% @orders.each do |order| %>
        <tbody>
          <tr>
            <td>
              <%= link_to admin_order_path(order.id) do %>
              <%= order.created_at.to_s(:datetime_jp) %>
              <% end %>
              </td>
            <td><%= order.customer.family_name %><%= order.customer.first_name %></td>
            <td><%= OrderProduct.where(order_id: order.id).sum(:quantity) %></td>
            <td><%= order.status %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</main>

app/views/admin/orders/show.html.erb
<div class="container">
  <br>
  <div class="row">
    <div class="col-6 mx-auto">
      <h3><span class="bg-secondary text-white">　注文履歴詳細　<br></span></h3><br>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <table class="table table-borderless">
        <tr>
          <th>購入者</th>
          <td>
            <%= link_to admin_customer_path(@order.customer.id) do %>
              <%= @order.customer.family_name %>　<%= @order.customer.first_name %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>〒<%= @order.postal_code %>　<%= @order.address %>　<br><%= @order.name %></td>
        </tr>
        <tr>
          <th>支払い方法</th>
          <td><%= @order.payment %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= form_with model: @order, url: admin_order_path, method: :patch, local: true do |f| %>
            <%= f.select :status, options_for_select(Order.statuses.keys, selected: @order.status), :class => "form-control" %>
            <%= f.submit "更新", :class => "btn btn-primary btn-sm" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <br>
  <div class="row justify-content-between">
    <div class="col-8 ordershow text-center">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th class="text-left">商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @order_products.each do |order_product| %>
            <tr></tr>
              <td class="text-left align-middle"><%= order_product.product.name %></td>
              <td class="align-middle"><%= ((order_product.product.tax_out_price).to_i * 1.1).round %></td>
              <td class="align-middle"><%= order_product.quantity %></td>
              <td class="align-middle"><%= ((order_product.product.tax_out_price).to_i * 1.1 * (order_product.quantity).to_i).round %></td>
              <td class="align-middle">
                <%= form_with model: order_product, url: order_creates_path(id: order_product.id), method: :patch, local: true do |f| %>
                  <%= f.select :status, options_for_select(OrderProduct.statuses.keys, selected: order_product.status)%>
              </td>
              <td>
                  <%= f.submit "更新", :class => "btn btn-primary btn-sm" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-3 align-self-end">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>商品合計</th>
            <td><%= @order.sum %>円</td>
          </tr>
          <tr>
            <th>送料</th>
            <td><%= @order.shipping %>円</td>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <td><b><%= @order.sum.to_i + @order.shipping.to_i %>円</b></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/top.html.erb
<div class="container">
  <br>
  <div class="row">
    <div class="col-6 mx-auto">
      <h3><span class="bg-secondary text-white">　管理者画面　</span></h3><br>
    </div>
  </div>
  <div class="row">
    <div class="col-6 mx-auto text-center">
    <h2>本日の注文件数　　　<u><%= link_to @todayorder.count, admin_orders_path(order_type: "today"), class: "text-dark" %></u> 件</h2>
    </div>
  </div>
</div>